### ISSUE TITLE
欧姆龙Fins的short数据读结果有误

### ISSUE THREAD

**Issue by jedtang** [zhaopeiym/IoTClient#18]
IoTClient Tool 欧姆龙Fins的short数据读写结果不一致,是ByteFormatting()方法漏了对2字节数据的变换?

**Comment by zhaopeiym** [comment]
你用的IoTClient Tool版本号是多少？更新下最新的试试。

**Comment by jedtang** [comment]
V1.1.0版本的已正常了， 谢谢！
