### ISSUE TITLE
Modbus 异常码没做处理导致异常查询后还返回成功

### ISSUE THREAD

**Issue by Assur** [zhaopeiym/IoTClient#26]
Modbus 83异常码没做处理，比如设备在响应报文01 82 01 81 60时，我调试源码发现没对80以上异常码做任何处理导致此时查询结果尽然是正常的，希望您能处理下异常码

**Comment by zhaopeiym** [comment]
nuget 更新 IoTClient 试下

**Comment by Assur** [comment]
感谢
