### ISSUE TITLE
能否增加直接读写字符串功能，像HslCommunication那样

### ISSUE THREAD

**Issue by Qiulin-Git** [zhaopeiym/IoTClient#6]

**Comment by zhaopeiym** [comment]
西门子的吗？

**Comment by Qiulin-Git** [comment]
> 西门子的吗？

目前公司西门子和三菱的PLC都有，我们现在用的是ModBus Tcp协议，希望ModBus 能直接读写字符串

**Comment by zhaopeiym** [comment]
可以安排上。

**Comment by zhaopeiym** [comment]
client.Write("100", "orderCode", stationNumber);  //写入字符串
client.ReadString("100", stationNumber,10);          //读取字符串
