### ISSUE TITLE
希望批量读取时增加地址别名

### ISSUE THREAD

**Issue by taohuaguo** [zhaopeiym/IoTClient#7]
![image](https://user-images.githubusercontent.com/28699500/117275591-c3e4af80-ae90-11eb-9386-11cd1deb0877.png)
因为地址可能会变化，因此增加地址别名作为参数唯一凭证，存入数据库时只保存地址别名和对应值；

**Comment by zhaopeiym** [comment]
不明白地址为什么会变化？

**Comment by taohuaguo** [comment]
和业务有关吧，部署到多客户多产线，每条产线同样的参数，但地址会不一样，程序里地址不能用死了。

**Comment by taohuaguo** [comment]
仔细想了一下，这个需求和业务关联性很强，可能其他人都不需要，就先关了这个issue吧。
