### ISSUE TITLE
西门子解析地址异常

### ISSUE THREAD

**Issue by taohuaguo** [zhaopeiym/IoTClient#8]
地址[DB400.DBX1.6]解析异常，ConvertArg Err:输入字符串的格式不正确。
大神晚上好，我是直接用的西门子客户端，类似DB400.DBX1.6这样的地址都会报错
![image](https://user-images.githubusercontent.com/28699500/118477773-a42b7200-b741-11eb-9827-5c3f695b2ebf.png)

**Comment by zhaopeiym** [comment]
请看使用文档：
https://github.com/zhaopeiym/IoTClient/blob/master/README-zh_CN.md#注意关于siemens的plc地址

“DB400.DBX1.6”  地址输入  “DB400.1.6” 即可。

**Comment by taohuaguo** [comment]
收到，可以了，谢谢
