### ISSUE TITLE
S400 插槽号问题

### ISSUE THREAD

**Issue by taohuaguo** [zhaopeiym/IoTClient#9]
![image](https://user-images.githubusercontent.com/28699500/119246569-2f2ec100-bbb5-11eb-9fe8-da7a53ec2111.png)
![image](https://user-images.githubusercontent.com/28699500/119246616-846ad280-bbb5-11eb-96b1-b067a37fc17a.png)
大神早上好，今天遇到一个问题，连接时IOTClient Tool提示连接被断开。用另外一款测试工具试了一下，里面可以修改插槽号，把插槽号改成2就正常连接了。咱们这个可以配置插槽号吗？

**Comment by taohuaguo** [comment]
![image](https://user-images.githubusercontent.com/28699500/119246916-11169000-bbb8-11eb-8d02-fdf841f5104c.png)
补充连接失败的图

**Comment by zhaopeiym** [comment]
菜单栏上的  “检查更新” 更新下版本试试看

**Comment by taohuaguo** [comment]
更新后工具可以了，程序里怎么用呢，需要引用最新IOTClient.dll吗

**Comment by zhaopeiym** [comment]
对的  

SiemensClient client = new SiemensClient(SiemensVersion.S7_400, "127.0.0.1",102,插槽号);

稍后，源码也会更新到github。

**Comment by taohuaguo** [comment]
好的，非常感谢！
